spring.application.name=backend
# Neon PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-frosty-term-b4s7bt8r-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_v3tcF2JXnAkY
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Pool settings for Neon serverless
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#port
server.port=9090
